### ISSUE TITLE
Shopware 6.4 Currency Format Issue

### ISSUE THREAD

**Issue by vekkon** [mmeester/mmeesSlackNotifier#4]
In the new shopware version 6.4 an error occures with the plugin on activation and on order creation.
The error prevents the order creation completely.

The issue is caused by an deprecated use of the CurrencyFormatter.
The CurrencyFormatter expects "Doctrine\DBAL\Connection" instead of "order.repository".
Also the use of the function formatCurrency is deprecated. Much more parameters are needed

**Comment by vekkon** [comment]
I already fixed the issue locally.
Could you create a branch in which I can push my fix?

**Comment by mmeester** [comment]
Hi Noah, feel free to fork the repo and create a PR.

**Comment by mmeester** [comment]
@noahming now that I read your issue better this is solved in the latest Release (1.1.1)
